version: '3'


services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - /opt/sonar/conf:/opt/sonarqube/conf
      - /opt/sonar/data:/opt/sonarqube/data
      - /opt/sonar/ext:/opt/sonarqube/extensions
      - /opt/sonar/plug:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /opt/post:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/    Dockerfile.template#L52
      - /opt/post/data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
